language: ruby
before_script:
- mysql -e 'create database blog_test;'
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
deploy:
  provider: openshift
  user: brainwired@gmail.com
  password:
    secure: ZmWcLUb8I6FD0fksOC4oTv98SEHJxNZpGNUakfSgebQ8VPyp4pjtIScoYq5p+r5xkAP7xeX/RFeUnH/kgmRMvjSc84Fyn7Izoo9TUqfBLhlWR/8Wu8aDX/srsaufKiN509oDdYfajjAt2noEa7GIaw+tlP9nyE8TN8x0BaZWXAuCwq6R5Hr/mRfzJtHJSnX0IbrsPTdQnLSqZRX2xfA0OiFrgiWG67RFZT9ZlgpVx++vSrtD5YLt5IR54e1TY2tVSlm4aGA53feQRNlSJi6IltUDWn9pPJ6CqV8aoXvS4FMkkbXJ3LzF+3Zz5lJJg0s3NPABH/kvoxdX8VL6RZYzWp5x50g9ZRdr95vPVS8v1Mtw2GnE5zmZXn/KAB1nACam4uWAMcDvvT3peOgfuRXwfpAh2VLmAaBBnW9zUzI+oTZ2Qev8IgEtB1q8Rz57VS9+39ktNCs4cDRn8x35Fi7uU1XqyBBRgqdAqL/Ufaeh/JiXwLERAx5VpaDgr12A/qKbXeXHRcGMM+GpPiWqqs8jtl3NWPzU64KPO7EC2K3H4Z+fVdwLg3P+Qkj9ruRtFQnNp012FRykkx3vN8vycqDUbd5P7dQzC9GCxOoqLJgnfuMdav9Ynmx401MFxUYJrDhOtoUp2KrNWAZEN83lSbOKCeHpcma0FQPvQ21jC66axhU=
  app: railsblog
  domain: 'railsblog-sudogem.rhcloud.com'
  on:
    repo: sudogem/rails-blog
