language: ruby
before_script:
- mysql -e 'create database blog_test;'
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
notifications:
  slack: pragmaticprogrammers:vPa5atxnsbHS6dTEuAAsnSxy
deploy:
  provider: script
  script: echo "Deployment disabled"
  skip_cleanup: true
  on:
    repo: sudogem/rails-blog
