# 2015-07-23 RICHARD:
# THIS IS A SAMPLE FOR social_keys.yml which is git-ignored as it should be, because it will have your keys in it.
# REMEMBER TO COPY THIS FILE TO social_keys.yml AND CHANGE THE KEYS IN THERE TO MATCH YOURS.
development:
  facebook_key: "186562331438905"
  facebook_secret: "e17c5c0e6a31d947e2bcfc9ca1f59ae5"

  twitter_key: "YuwrW1nXUzHuzjpE451sdLCas"
  twitter_secret: "ZrJsvpZhXg8qhj2xkXsYGjdwcDzv39MlqnfjMTNb0WyU3hXEiC"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "75log5tdatsc5w"
  linkedin_secret: "zN33CTRbJm1vNdL2"
  ## In LinkedIn Developers, add the ff. settings 
  ## OAuth2 Authorized Redirect URL: http://localhost:3000/users/auth/linkedin/callback

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

production:
  facebook_key: "YOUR_KEY"
  facebook_secret: "YOUR_SECRET"

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
